In [28]:
import os
import cv2
import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.model_selection import train_test_split
from keras import layers, models
import tensorflow as tf

# Funkcja wczytująca obrazy i etykiety z folderu i pliku CSV
def load_data(folder_path, csv_path):
    data = pd.read_csv(csv_path).values
    images = []
    labels = []
    counter=1

    for index, row in enumerate(os.listdir(folder_path)):
        image_path = os.path.join(folder_path, row)
        if data[index][1:].max() > 1:
            continue
        image = cv2.imread(image_path)
        image = cv2.resize(image, (224, 224))  # Dostosuj rozmiar obrazów do wymagań modelu
        image  = cv2.normalize(image,  None, 0, 1, cv2.NORM_MINMAX)
        print(data[index][1:])
        images.append(image)
        labels.append(data[index][1:])
        counter+=1

    return np.array(images), np.array(labels)

# Wczytaj dane
folder_path = 'C:\\Users\\tom19\\VScode_Projects\\Computer_vision\\klocki_do_uczenia\\klocki_wyciete_surowe\\'
csv_path = 'C:\\Users\\tom19\\VScode_Projects\\Computer_vision\\generated_data.csv'
images, labels = load_data(folder_path, csv_path)

# Podział danych na zbiór treningowy i testowy
X_train, X_test, y_train, y_test = train_test_split(images, labels, test_size=0.2, random_state=42)

# Definicja modelu CNN
cnn = tf.keras.models.Sequential()
cnn.add(tf.keras.layers.Conv2D(kernel_size=3, filters=32, activation='relu', input_shape=[224,224,3])) #convolution
cnn.add(tf.keras.layers.MaxPool2D(pool_size=2, strides=2))  #pooling

cnn.add(tf.keras.layers.Conv2D(kernel_size=3, filters=32, activation='relu')) #convolution 2
cnn.add(tf.keras.layers.MaxPool2D(pool_size=2, strides=2))  #pooling 2

cnn.add(tf.keras.layers.Flatten())  #flattening

cnn.add(tf.keras.layers.Dense(units=128, activation='relu'))  #full connection
cnn.add(tf.keras.layers.Dense(units=32, activation='relu'))  #hidden
cnn.add(tf.keras.layers.Dense(units=8, activation='sigmoid')) #output layer

# Kompilacja modelu
cnn.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

# Ustawienia dotyczące rozmiaru partii
batch_size = 50

# Trenowanie modelu
cnn.fit(X_train, y_train, epochs=10, batch_size=batch_size, validation_data=(X_test, y_test))

# Ocenianie modelu na danych testowych
test_loss, test_acc = cnn.evaluate(X_test, y_test)
print(f'Test accuracy: {test_acc}')



[0 0 0 0 1 0 0 0]
[0 0 0 0 1 0 0 0]
[0 0 0 0 1 0 0 0]
[0 0 0 0 1 0 0 0]
[0 0 0 0 1 0 0 0]
[0 0 0 0 1 0 0 0]
[0 0 0 0 1 0 0 0]
[0 0 0 0 1 0 0 0]
[0 0 0 0 1 0 0 0]
[0 0 0 0 1 0 0 0]
[0 0 0 0 1 0 0 0]
[0 0 0 0 1 0 0 0]
[1 0 0 0 0 0 0 0]
[1 0 0 0 0 0 0 0]
[1 0 0 0 0 0 0 0]
[1 0 0 0 0 0 0 0]
[1 0 0 0 0 0 0 0]
[1 0 0 0 0 0 0 0]
[1 0 0 0 0 0 0 0]
[1 0 0 0 0 0 0 0]
[1 0 0 0 0 0 0 0]
[1 0 0 0 0 0 0 0]
[1 0 0 0 0 0 0 0]
[1 0 0 0 0 0 0 0]
[1 0 0 0 0 0 0 0]
[1 0 0 0 0 0 0 0]
[0 1 0 0 0 0 0 0]
[1 0 0 0 0 0 0 0]
[1 0 0 0 0 0 0 0]
[1 0 0 0 0 0 0 0]
[1 0 0 0 0 0 0 0]
[1 0 0 0 0 0 0 0]
[0 0 0 0 0 1 0 0]
[0 0 0 0 0 1 0 0]
[0 0 0 0 1 0 0 0]
[0 0 0 0 1 0 0 0]
[1 0 0 0 0 0 0 0]
[1 0 0 0 0 0 0 0]
[1 0 0 1 0 0 0 0]
[1 0 0 0 0 0 0 0]
[1 0 0 0 0 0 0 0]
[0 0 0 1 0 0 0 0]
[0 0 0 1 0 0 0 0]
[1 0 0 0 0 0 0 0]
[0 1 0 0 0 0 0 0]
[1 0 0 0 0 0 0 0]
[1 0 0 0 0 0 0 0]
[1 0 0 0 0 0 0 0]
[0 0 0 1 0 0 0 0]
[1 0 0 0 0 0 0 0]
[1 0 0 0 0 0 0 1]
[0 0 1 0 0 0 0 0]
[1 1 0 0 0 0 0 0]
[1 0 0 0 0 0 0 0]
[1 0 0 0 0 0 0 0]
[1 0 0 0 0

In [32]:
path = 'C:\\Users\\tom19\\VScode_Projects\\Computer_vision\\klocki_do_uczenia\\klocki_wyciete_surowe\\klocek301.png'
img1 = X_train[0]
img = cv2.imread(path)
img = cv2.resize(img, (224, 224))
img  = cv2.normalize(img,  None, 0, 1, cv2.NORM_MINMAX)
cnn.predict(np.array([img]))

[[0 0 0 ... 0 0 1]
 [1 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 ...
 [0 1 0 ... 1 0 0]
 [0 0 0 ... 0 1 0]
 [0 1 0 ... 0 0 0]]
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
(224, 224, 3)
1/1 [==============================] - 0s 26ms/step


array([[3.2686986e-02, 5.7034081e-06, 7.6352521e-03, 1.4472579e-03,
        2.8914408e-04, 9.9760610e-01, 5.0611898e-06, 1.5831046e-02]],
      dtype=float32)